<?php

namespace Proxies\__CG__\Project\SedBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DetallePregunta extends \Project\SedBundle\Entity\DetallePregunta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCalificacion($calificacion)
    {
        $this->__load();
        return parent::setCalificacion($calificacion);
    }

    public function getCalificacion()
    {
        $this->__load();
        return parent::getCalificacion();
    }

    public function setComentario($comentario)
    {
        $this->__load();
        return parent::setComentario($comentario);
    }

    public function getComentario()
    {
        $this->__load();
        return parent::getComentario();
    }

    public function setPregunta(\Project\SedBundle\Entity\Pregunta $pregunta = NULL)
    {
        $this->__load();
        return parent::setPregunta($pregunta);
    }

    public function getPregunta()
    {
        $this->__load();
        return parent::getPregunta();
    }

    public function setIdCurso(\Project\SedBundle\Entity\Curso $idCurso = NULL)
    {
        $this->__load();
        return parent::setIdCurso($idCurso);
    }

    public function getIdCurso()
    {
        $this->__load();
        return parent::getIdCurso();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'calificacion', 'comentario', 'pregunta', 'idCurso');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}