<?php

namespace Proxies\__CG__\Project\SedBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Materia extends \Project\SedBundle\Entity\Materia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setCreditos($creditos)
    {
        $this->__load();
        return parent::setCreditos($creditos);
    }

    public function getCreditos()
    {
        $this->__load();
        return parent::getCreditos();
    }

    public function setNoSemestre($noSemestre)
    {
        $this->__load();
        return parent::setNoSemestre($noSemestre);
    }

    public function getNoSemestre()
    {
        $this->__load();
        return parent::getNoSemestre();
    }

    public function setPrograma(\Project\SedBundle\Entity\Programa $programa = NULL)
    {
        $this->__load();
        return parent::setPrograma($programa);
    }

    public function getPrograma()
    {
        $this->__load();
        return parent::getPrograma();
    }

    public function addCurso(\Project\SedBundle\Entity\Curso $cursos)
    {
        $this->__load();
        return parent::addCurso($cursos);
    }

    public function removeCurso(\Project\SedBundle\Entity\Curso $cursos)
    {
        $this->__load();
        return parent::removeCurso($cursos);
    }

    public function getCursos()
    {
        $this->__load();
        return parent::getCursos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigo', 'nombre', 'creditos', 'noSemestre', 'programa', 'cursos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}