<?php

namespace Proxies\__CG__\Project\SedBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Docente extends \Project\SedBundle\Entity\Docente implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCedula($cedula)
    {
        $this->__load();
        return parent::setCedula($cedula);
    }

    public function getCedula()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["cedula"];
        }
        $this->__load();
        return parent::getCedula();
    }

    public function setNombres($nombres)
    {
        $this->__load();
        return parent::setNombres($nombres);
    }

    public function getNombres()
    {
        $this->__load();
        return parent::getNombres();
    }

    public function setApellidos($apellidos)
    {
        $this->__load();
        return parent::setApellidos($apellidos);
    }

    public function getApellidos()
    {
        $this->__load();
        return parent::getApellidos();
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function addCurso(\Project\SedBundle\Entity\Curso $cursos)
    {
        $this->__load();
        return parent::addCurso($cursos);
    }

    public function removeCurso(\Project\SedBundle\Entity\Curso $cursos)
    {
        $this->__load();
        return parent::removeCurso($cursos);
    }

    public function getCursos()
    {
        $this->__load();
        return parent::getCursos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'cedula', 'nombres', 'apellidos', 'titulo', 'foto', 'cursos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}