parameters:
#    project_sed.example.class: Project\SedBundle\Example

services:
#    project_sed.example:
#        class: %project_sed.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
